### Create a new product
POST http://localhost:8080/products
Content-Type: application/json

{
  "id": 23,
  "name": "Desktop",
  "price": 1200.50,
  "inventory": 10,
  "category_id": 2,
  "created_at": "2025-09-17T12:00:00Z",
  "updated_at": "2025-09-17T12:00:00Z"
}

### Get all products (from read model)
GET http://localhost:8080/products
Accept: application/json
